### ISSUE TITLE
how to use it when using docker-compose

### ISSUE THREAD

**Issue by timnick-snow** [data-diving/superset-xlsx#4]
how to use it when using docker-compose

**Comment by aleksandrgordienko** [comment]
Hey,

You can build image and use it instead of official one with community-provided [docker-compose.yml](https://github.com/apache/superset/blob/1.4.1/docker-compose.yml).

To do so, you have to replace this line:
`x-superset-image: &superset-image apache/superset:latest-dev`
with this
`x-superset-image: &superset-image data-diving/superset-xlsx`
